/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bee.correo.util;

/**
 *
 * @author Lealva
 */
public class CuerpoEnvioDocumentosVenta {

    public String CuerpoEnvio() {
        String cuerpo = "<!DOCTYPE html>\n"
                + "<html lang=\"es\" xmlns=\"http://www.w3.org/1999/xhtml\">\n"
                + "\n"
                + "<head>\n"
                + "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n"
                + "  <link href=\"https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700&display=swap\" rel=\"stylesheet\">\n"
                + "  <title>Plataforma at Work</title>\n"
                + "  <style type=\"text/css\">\n"
                + "    @media only screen and (max-width: 550px),\n"
                + "    screen and (max-device-width: 550px) {\n"
                + "\n"
                + "      .button {\n"
                + "        font-size: 10px !important;\n"
                + "      }\n"
                + "\n"
                + "      .tr {\n"
                + "        /* background-color: teal; */\n"
                + "\n"
                + "      }\n"
                + "\n"
                + "      .td {\n"
                + "        height: 8rem !important;\n"
                + "      }\n"
                + "\n"
                + "      .img {\n"
                + "        width: 95% !important;\n"
                + "      }\n"
                + "\n"
                + "\n"
                + "    }\n"
                + "  </style>\n"
                + "</head>\n"
                + "\n"
                + "<body yahoo=\"\" style=\"font-family: 'Montserrat', sans-serif;\">\n"
                + "\n"
                + "  <table style=\"margin:0 auto\">\n"
                + "    <thead>\n"
                + "      <tr>\n"
                + "        <th>\n"
                + "          <img class=\"img\" src=\"https://i.pinimg.com/originals/eb/10/ed/eb10ed06ecf905c4c0d401aba816562a.png\" alt=\"\" style=\"width: 75%; padding-top: 2rem;\">\n"
                + "        </th>\n"
                + "      </tr>\n"
                + "    </thead>\n"
                + "    <tbody style=\"margin-top: -2rem; padding:0;\">\n"
                + "\n"
                + "      <tr>\n"
                + "        <td>\n"
                + "          <p style=\"text-align: center;\n"
                + "            font-size: 1.3rem;\n"
                + "            font-weight: 400;\n"
                + "            padding-bottom:0;\n"
                + "            margin-bottom: 1rem;\n"
                + "            line-height: normal;\n"
                + "            margin-top:1.5rem;\">\n"
                + "            <span style=\"font-weight: 600;\">Descarga los códigos</span> de tus entradas y combos <br>\n"
                + "            y <span style=\"font-weight: 600;\">canjéalos en la web </span>\n"
                + "            <a href=\"https://www.cineplanet.com.pe/\" target=\"_blank\">www.cineplanet.com.pe</a>\n"
                + "            <br>\n"
                + "            o desde tu celular <span style=\"font-weight: 600;\">a través de la app de Cineplanet.</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "      <tr class=\"tr\" style=\"height:80px; width:100%;text-align: center;\">\n"
                + "        <td class=\"td\" style=\"padding:0;\">\n"
                + "          <a class=\"button\" style=\"color: black;\n"
                + "            background-color: #F4C700;\n"
                + "            padding:1rem;\n"
                + "            width: auto;\n"
                + "            border-radius: 7px;\n"
                + "            text-align: center;\n"
                + "            font-weight: 600;\n"
                + "            font-size: 12px;\n"
                + "            \">\n"
                + "            DESCARGA AQUÍ TUS ENTRADAS Y COMBOS\n"
                + "          </a>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr>\n"
                + "        <td>\n"
                + "          <p style=\"text-align: center;\n"
                + "            font-size: 1.3rem;\n"
                + "            font-weight: 400;\n"
                + "            padding-bottom:0;\n"
                + "            margin-bottom: 1rem;\n"
                + "            line-height: normal;\n"
                + "            margin-top:1.5rem;\">\n"
                + "            Para consultar en línea tus comprobantes de pago ingresa\n"
                + "            <a href=\"https://miscomprobantes.yastaintegrado.pe/\" target=\"_blank\">aquí</a>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "\n"
                + "\n"
                + "      <tr style=\"height:30px;\">\n"
                + "        <td>\n"
                + "          <p style=\"text-align: center;\n"
                + "      font-size: 1.4rem;\n"
                + "      font-weight: bold;\n"
                + "      padding-bottom:0;\n"
                + "      margin-bottom: 0;\n"
                + "      line-height: normal;\n"
                + "      margin-top:1.3rem;\">\n"
                + "            ¡Disfruta tu película!\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"height:30px;\">\n"
                + "        <td>\n"
                + "          <hr style=\"height: 4px;\n"
                + "          background-color: #177799;\n"
                + "          border: none;\n"
                + "          width: 75%;\n"
                + "          margin-top:1.5rem;\n"
                + "          \">\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "\n"
                + "      <tr style=\"height:30px;\">\n"
                + "        <td>\n"
                + "          <p style=\"text-align: center;\n"
                + "      font-size: 1.2rem;\n"
                + "      font-weight: 400;\n"
                + "      padding-bottom:0;\n"
                + "      line-height: normal;\n"
                + "      margin-bottom: 0;\n"
                + "      margin-top:1.5rem;\">\n"
                + "            Si tuvieras alguna duda, escríbenos a:\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"height:30px;\">\n"
                + "        <td>\n"
                + "          <p style=\"text-align: center;\n"
                + "          font-size: 1.2rem;\n"
                + "          font-weight: bold;\n"
                + "          padding-bottom:0;\n"
                + "          line-height: normal;\n"
                + "          margin-bottom: 1rem;\n"
                + "          margin-top:0;\n"
                + "          \">\n"
                + "            atencionalcliente@bee.com.pe\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr>\n"
                + "        <td>\n"
                + "          <p style=\"text-align: center;\n"
                + "      font-size: 1.2rem;\n"
                + "      font-weight: 400;\n"
                + "      padding-bottom:0;\n"
                + "      margin-bottom: 0;\n"
                + "      line-height: normal;\n"
                + "      margin-top:.3rem;\">\n"
                + "            o llámanos al:\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr>\n"
                + "        <td>\n"
                + "          <p style=\"text-align: center;\n"
                + "          font-size: 1.2rem;\n"
                + "          font-weight: bold;\n"
                + "          padding-bottom:0;\n"
                + "          line-height: normal;\n"
                + "          margin-bottom: 1rem;\n"
                + "          margin-top:0;\">\n"
                + "            (01) 640-9699\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "\n"
                + "      <tr>\n"
                + "        <td>\n"
                + "          <img class=\"img\" src=\"https://i.pinimg.com/originals/b2/31/80/b231803c987e717c9e444489ac7fb480.jpg\" alt=\"\" style=\"\n"
                + "        width: 75%;\n"
                + "        padding-top: 2rem;\n"
                + "        display: block;\n"
                + "        margin: 0 auto;\n"
                + "        \">\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "\n"
                + "    </tbody>\n"
                + "\n"
                + "  </table>\n"
                + "</body>\n"
                + "\n"
                + "</html>";
        return cuerpo;
    }
}
