/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bee.correo.util;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author RAYP
 */
public class CuerpoEnvioLibrorec {
    
    java.util.Date fecha = new Date();
    String strDateFormat = "dd-MM-yyyy"; 
    SimpleDateFormat objSDF = new SimpleDateFormat(strDateFormat);  
    String fecfinal = objSDF.format(fecha);
    
    public String cuerpolibrorec_callcenter(String detallestr) {
        String[] parts;
        parts = detallestr.split("¦");
        String cuerpo = "<!DOCTYPE html>\n"
                + "<html lang=\"es\" xmlns=\"http://www.w3.org/1999/xhtml\">\n"
                + "\n"
                + "<head>\n"
                + "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n"
                + "<title>Call center</title>\n"
                + "<style type=\"text/css\">\n"
                + "    @media (max-width: 550px) {\n"
                + "\n"
                + "      .button { \n"
                + "        font-size: 10px !important; \n"
                + "      }\n"
                + "\n"
                + "      .tr {\n"
                + "        /* background-color: teal; */ \n"
                + "\n"
                + "      }\n"
                + "\n"
                + "      td {\n"
                + "        height: 8rem !important;\n"
                + "        font-size; \n"
                + "        5rem; \n"
                + "      }  \n"
                + "\n"
                + "      img {\n"
                + "        display: block;\n"
                + "\n"
                + "      }\n"
                + "\n"
                + "\n"
                + "    }\n"
                + "  </style>\n"
                + "</head>\n"
                + "\n"
                + "<body yahoo=\"\" style=\"font-family:arial;\">\n"
                + "\n"
                + "  <table style=\"margin:0 auto; max-width:600px;\">\n"
                + "    <thead>\n"
                + "\n"
                + "      <tr>\n"
                + "        <th style=\"background-color: #042355;\">\n"
                + "          <img class=\"img\" src=\"https://i.pinimg.com/originals/74/e2/c1/74e2c1ea5c12c19f2996f1158fe3a60a.png\" alt=\"\" style=\"width: 50%;padding:7px 1px 1px 1px;\">\n"
                + "        </th>\n"
                + "      </tr>\n"
                + "    </thead>\n"
                + "\n"
                + "    <tbody style=\"margin-top: -2rem; padding:0; color:#001D4C;\">\n"
                + "\n"
                + "      <tr style=\"font-size: 18px;\">\n"
                + "        <td>\n"
                + "\n"
                + "          <hr style=\"height: 2px; background-color: #042355; \">\n"
                + "\n"
                + "          <div style=\"width:100%; margin:0 auto;\">\n"
                + "            <p style=\"text-align:center; line-height: 1.7rem; \">\n"
                + "              Se ha ingresado un nuevo registro en el Libro de Reclamaciones,\n"
                + "              recuerda que el plazo máximo para atenderlo es de 48 horas.\n"
                + "            </p>\n"
                + "          </div>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <hr style=\"height: 2px; background-color: #042355;\">\n"
                + "\n"
                + "          <h1>Libro de reclamaciones</h1>                                    \n"
                + "\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Hoja de Reclamación Nº: <span style=\"color:#6F6F6F\">\n"
                + parts[17]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Fecha: <span style=\"color:#6F6F6F\">\n"
                + fecfinal
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "\n"
                + "      <tr style=\"height:30px;\">\n"
                + "        <td>\n"
                + "          <hr style=\"height: 2px;background-color: #042355\"> \n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <h3 style=\"line-height: 1rem;\">\n"
                + "            01. Datos del consumidor\n"
                + "          </h3>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Nombres: <span style=\"color:#6F6F6F\">\n"
                + parts[0]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Apellidos: <span style=\"color:#6F6F6F\">\n"
                + parts[1]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Tipo de documento: <span style=\"color:#6F6F6F\">\n"
                + parts[2]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Número de documento: <span style=\"color:#6F6F6F\">\n"
                + parts[3]
                + "</span> \n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Departamento: <span style=\"color:#6F6F6F\">\n"
                + parts[4]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Provincia: <span style=\"color:#6F6F6F\">\n"
                + parts[5]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Distrito: <span style=\"color:#6F6F6F\">\n"
                + parts[6]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Dirección: <span style=\"color:#6F6F6F\">\n"
                + parts[7]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Teléfono: <span style=\"color:#6F6F6F\">\n"
                + parts[8]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Email: <span style=\"color:#6F6F6F\">\n"
                + parts[9]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "\n"
                + "      <tr style=\"height:30px;\">\n"
                + "        <td>\n"
                + "          <hr style=\"height: 2px;background-color: #042355\">\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <h3 style=\"line-height: 1rem;\">\n"
                + "            02. Datos del bien contratado\n"
                + "          </h3>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Área de ocurrencia: <span style=\"color:#6F6F6F\">\n"
                + parts[10]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Motivo: <span style=\"color:#6F6F6F\">\n"
                + parts[11]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Monto reclamado: <span style=\"color:#6F6F6F\">\n"
                + parts[12]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Descripción del bien contratado: <span style=\"color:#6F6F6F\">\n"
                + parts[13]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"height:30px;\">\n"
                + "        <td>\n"
                + "          <hr style=\"height: 2px;background-color: #042355\">\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <h3 style=\"line-height: 1rem;\">\n"
                + "            03. Detalle del reclamo\n"
                + "          </h3>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Tipo: <span style=\"color:#6F6F6F\">\n"
                + parts[14]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td style=\"display:flex; max-width: 600px;\">\n"
                + "          <div style=\" width: 25%\">\n"
                + "            <p style=\"line-height: .5rem; max-width:600px; line-height:1.2rem\">\n"
                + "              Detalle:\n"
                + "            </p>\n"
                + "          </div>\n"
                + "\n"
                + "          <div style=\"width: 100%; padding-top:1rem;\">\n"
                + "            <span style=\"color:#6F6F6F\">\n"
                + parts[15]
                + "            </span>\n"
                + "\n"
                + "          </div>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Pedido: <span style=\"color:#6F6F6F\">\n"
                + parts[16]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"               
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "\n"
                + "\n"
                + "    </tbody>\n"
                + "\n"
                + "  </table>\n"
                + "</body>\n"
                + "\n"
                + "</html>\n";
        return cuerpo;
    }

    public String cuerpolibrorec_cliente(String detallestr) {
        String[] parts;
        parts = detallestr.split("¦");

        String cuerpo = "<!DOCTYPE html>\n"
                + "<html lang=\"es\" xmlns=\"http://www.w3.org/1999/xhtml\">\n"
                + "\n"
                + "<head>\n"
                + "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n"
                + "  <title>Cliente</title>\n"
                + "  <style type=\"text/css\">\n"
                + "    @media (max-width: 550px) {\n"
                + "\n"
                + "      .button {\n"
                + "        font-size: 10px !important;\n"
                + "      }\n"
                + "\n"
                + "      .tr {\n"
                + "        /* background-color: teal; */\n"
                + "\n"
                + "      }\n"
                + "\n"
                + "      td {\n"
                + "        height: 8rem !important;\n"
                + "        font-size;\n"
                + "        5rem;\n"
                + "      }\n"
                + "\n"
                + "      img {\n"
                + "        display: block;\n"
                + "      }\n"
                + "    }\n"
                + "  </style>\n"
                + "</head>\n"
                + "\n"
                + "<body yahoo=\"\" style=\"font-family:arial;\">\n"
                + "\n"
                + "  <table style=\"margin:0 auto; max-width:600px;\">\n"
                + "    <thead>\n"
                + "\n"
                + "      <tr>\n"
                + "        <th style=\"background-color: #042355;\">\n"
                + "          <img class=\"img\" src=\"https://i.pinimg.com/originals/74/e2/c1/74e2c1ea5c12c19f2996f1158fe3a60a.png\" alt=\"\" style=\"width: 50%;padding:7px 1px 1px 1px;\">\n"
                + "        </th>\n"
                + "      </tr>\n"
                + "    </thead>\n"
                + "\n"
                + "    <tbody style=\"margin-top: -2rem; padding:0; color:#001D4C;\">\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <hr style=\"height: 2px; background-color: #042355;\">\n"
                + "\n"
                + "          <h1>Libro de reclamaciones</h1>\n"
                + "\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Hoja de Reclamación Nº: <span style=\"color:#6F6F6F\">\n"
                + parts[17]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Fecha: <span style=\"color:#6F6F6F\">\n"
                + fecfinal
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"height:30px;\">\n"
                + "        <td>\n"
                + "          <hr style=\"height: 2px;background-color: #042355\">\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <h3 style=\"line-height: 1rem;\">\n"
                + "            01. Datos del consumidor\n"
                + "          </h3>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Nombres: <span style=\"color:#6F6F6F\">\n"
                + parts[0]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Apellidos: <span style=\"color:#6F6F6F\">\n"
                + parts[1]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Tipo de documento: <span style=\"color:#6F6F6F\">\n"
                + parts[2]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Número de documento: <span style=\"color:#6F6F6F\">\n"
                + parts[3]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Departamento: <span style=\"color:#6F6F6F\">\n"
                + parts[4]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Provincia: <span style=\"color:#6F6F6F\">\n"
                + parts[5]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Distrito: <span style=\"color:#6F6F6F\">\n"
                + parts[6]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Dirección: <span style=\"color:#6F6F6F\">\n"
                + parts[7]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Teléfono: <span style=\"color:#6F6F6F\">\n"
                + parts[8]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Email: <span style=\"color:#6F6F6F\">"
                + parts[9]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"height:30px;\">\n"
                + "        <td>\n"
                + "          <hr style=\"height: 2px;background-color: #042355\">\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <h3 style=\"line-height: 1rem;\">\n"
                + "            02. Datos del bien contratado\n"
                + "          </h3>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Área de ocurrencia: <span style=\"color:#6F6F6F\">\n"
                + parts[10]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Motivo: <span style=\"color:#6F6F6F\">"
                + parts[11]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Monto reclamado: <span style=\"color:#6F6F6F\">\n"
                + parts[12]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Descripción del bien contratado: <span style=\"color:#6F6F6F\">\n"
                + parts[13]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"height:30px;\">\n"
                + "        <td>\n"
                + "          <hr style=\"height: 2px;background-color: #042355\">\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <h3 style=\"line-height: 1rem;\">\n"
                + "            03. Detalle del reclamo\n"
                + "          </h3>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Tipo: <span style=\"color:#6F6F6F\">\n"
                + parts[14]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td style=\"display:flex; max-width: 600px;\">\n"
                + "          <div style=\" width: 25%\">\n"
                + "            <p style=\"line-height: .5rem; max-width:600px; line-height:1.2rem\">\n"
                + "              Detalle:\n"
                + "            </p>\n"
                + "          </div>\n"
                + "\n"
                + "          <div style=\" width: 100%; padding-top:1rem;\">\n"
                + "            <span style=\"color:#6F6F6F\">\n"
                + parts[15]
                + "            </span>\n"
                + "\n"
                + "          </div>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Pedido: <span style=\"color:#6F6F6F\">\n"
                + parts[16]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"height:30px;\">\n"
                + "        <td>\n"
                + "          <hr style=\"height: 2px;background-color: #042355;\">\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"font-size: 22px;\">\n"
                + "        <td>\n"
                + "          <div style=\"width:90%; margin:0 auto;\">\n"
                + "            <p style=\" text-align:center; line-height: 1.7rem; \">\n"
                + "              La respuesta a su reclamo será remitida al correo registrado\n"
                + "              en un plazo máximo de 48 horas.\n"
                + "            </p>\n"
                + "          </div>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "    </tbody>\n"
                + "\n"
                + "  </table>\n"
                + "</body>\n"
                + "\n"
                + "</html>\n";
        return cuerpo;
    }

    public String cuerpolibrorec_supervisor(String detallestr) {
        String[] parts;
        parts = detallestr.split("¦");

        String cuerpo = "<!DOCTYPE html>\n"
                + "<html lang=\"es\" xmlns=\"http://www.w3.org/1999/xhtml\">\n"
                + "\n"
                + "<head>\n"
                + "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n"
                + "  <title>Supervisor</title>\n"
                + "  <style type=\"text/css\">\n"
                + "    @media (max-width: 550px) {\n"
                + "\n"
                + "      .button {\n"
                + "        font-size: 10px !important;\n"
                + "      }\n"
                + "\n"
                + "      .tr {\n"
                + "        /* background-color: teal; */\n"
                + "\n"
                + "      }\n"
                + "\n"
                + "      td {\n"
                + "        height: 8rem !important;\n"
                + "        font-size;\n"
                + "        5rem;\n"
                + "      }\n"
                + "\n"
                + "      img {\n"
                + "        display: block;\n"
                + "\n"
                + "      }\n"
                + "\n"
                + "\n"
                + "    }\n"
                + "  </style>\n"
                + "</head>\n"
                + "\n"
                + "<body yahoo=\"\" style=\"font-family:arial;\">\n"
                + "\n"
                + "  <table style=\"margin:0 auto; max-width:600px;\">\n"
                + "    <thead>\n"
                + "\n"
                + "      <tr>\n"
                + "        <th style=\"background-color: #042355;\">\n"
                 + "          <img class=\"img\" src=\"https://i.pinimg.com/originals/74/e2/c1/74e2c1ea5c12c19f2996f1158fe3a60a.png\" alt=\"\" style=\"width: 50%;padding:7px 1px 1px 1px;\">\n"
                + "        </th>\n"
                + "      </tr>\n"
                + "    </thead>\n"
                + "\n"
                + "    <tbody style=\"margin-top: -2rem; padding:0; color:#001D4C;\">\n"
                + "\n"
                + "      <tr style=\"font-size: 18px;\">\n"
                + "        <td>\n"
                + "\n"
                + "          <hr style=\"height: 2px; background-color: #042355;\">\n"
                + "\n"
                + "          <div style=\"width:100%; margin:0 auto;\">\n"
                + "            <p style=\"text-align:center; line-height: 1.7rem; \">\n"
                + "              El siguiente registro ha sido ingresado al Libro de Reclamaciones\n"
                + "              hace 24 horas y no ha tenido respuesta. Recuerda que el plazo\n"
                + "              máximo para su atención es de 48 horas.\n"
                + "            </p>\n"
                + "          </div>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <hr style=\"height: 2px; background-color: #042355;\">\n"
                + "\n"
                + "          <h1>Libro de reclamaciones</h1>\n"
                + "\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Hoja de Reclamación Nº: <span style=\"color:#6F6F6F\">\n"
                + parts[17]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Fecha: <span style=\"color:#6F6F6F\">\n"
                + fecfinal
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"height:30px;\">\n"
                + "        <td>\n"
                + "          <hr style=\"height: 2px;background-color: #042355\">\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <h3 style=\"line-height: 1rem;\">\n"
                + "            01. Datos del consumidor\n"
                + "          </h3>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Nombres: <span style=\"color:#6F6F6F\">\n"
                + parts[0]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Apellidos: <span style=\"color:#6F6F6F\">\n"
                + parts[1]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Tipo de documento: <span style=\"color:#6F6F6F\">\n"
                + parts[2]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Número de documento: <span style=\"color:#6F6F6F\">\n"
                + parts[3]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Departamento: <span style=\"color:#6F6F6F\">\n"
                + parts[4]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Provincia: <span style=\"color:#6F6F6F\">\n"
                + parts[5]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Distrito: <span style=\"color:#6F6F6F\">\n"
                + parts[6]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Dirección: <span style=\"color:#6F6F6F\">\n"
                + parts[7]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Teléfono: <span style=\"color:#6F6F6F\">\n"
                + parts[8]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Email: <span style=\"color:#6F6F6F\">\n"
                + parts[9]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"height:30px;\">\n"
                + "        <td>\n"
                + "          <hr style=\"height: 2px;background-color: #042355\">\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <h3 style=\"line-height: 1rem;\">\n"
                + "            02. Datos del bien contratado\n"
                + "          </h3>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Área de ocurrencia: <span style=\"color:#6F6F6F\">\n"
                + parts[10]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Motivo: <span style=\"color:#6F6F6F\">\n"
                + parts[11]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Monto reclamado: <span style=\"color:#6F6F6F\">\n"
                + parts[12]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Descripción del bien contratado: <span style=\"color:#6F6F6F\">"
                + parts[13]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"height:30px;\">\n"
                + "        <td>\n"
                + "          <hr style=\"height: 2px;background-color: #042355\">\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <h3 style=\"line-height: 1rem;\">\n"
                + "            03. Detalle del reclamo\n"
                + "          </h3>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Tipo: <span style=\"color:#6F6F6F\">\n"
                + parts[14]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td style=\"display:flex; max-width: 600px;\">\n"
                + "          <div style=\" width: 25%\">\n"
                + "            <p style=\"line-height: .5rem; max-width:600px; line-height:1.2rem\">\n"
                + "              Detalle:\n"
                + "            </p>\n"
                + "          </div>\n"
                + "\n"
                + "          <div style=\" width: 100%; padding-top:1rem;\">\n"
                + "            <span style=\"color:#6F6F6F\">\n"
                + parts[15]
                + "            </span>\n"
                + "\n"
                + "          </div>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "            Pedido: <span style=\"color:#6F6F6F\">\n"
                + parts[16]
                + "</span>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "    </tbody>\n"
                + "\n"
                + "  </table>\n"
                + "</body>\n"
                + "\n"
                + "</html>\n";

        return cuerpo;
    }

    public String cuerpolibrorec_respcli(String detallestr) {
        String[] parts;
        parts = detallestr.split("¦");//(libMd.getCorrelativo()+ "¦"+libMd.getNombre() +"¦" + libMd.getResp() + "¦"+libMd.getFechtext());
        
        String cuerpo = "<!DOCTYPE html>\n"
                + "<html lang=\"es\" xmlns=\"http://www.w3.org/1999/xhtml\">\n"
                + "\n"
                + "<head>\n"
                + "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n"
                + "  <title>Respuesta-Cliente</title>\n"
                + "  <style type=\"text/css\">\n"
                + "    @media (max-width: 550px) {\n"
                + "\n"
                + "      .button {\n"
                + "        font-size: 10px !important;\n"
                + "      }\n"
                + "\n"
                + "      .tr {\n"
                + "        /* background-color: teal; */\n"
                + "\n"
                + "      }\n"
                + "\n"
                + "      td {\n"
                + "        height: 8rem !important;\n"
                + "        font-size;\n"
                + "        5rem;\n"
                + "      }\n"
                + "\n"
                + "      img {\n"
                + "        display: block;\n"
                + "\n"
                + "      }\n"
                + "\n"
                + "    }\n"
                + "  </style>\n"
                + "</head>\n"
                + "\n"
                + "<body yahoo=\"\" style=\"font-family:arial;\">\n"
                + "\n"
                + "  <table style=\"margin:0 auto; max-width:600px;\">\n"
                + "    <thead>\n"
                + "\n"
                + "      <tr>\n"
                + "        <th style=\"background-color: #042355;\" >\n"
                + "          <img class=\"img\" src=\"https://i.pinimg.com/originals/74/e2/c1/74e2c1ea5c12c19f2996f1158fe3a60a.png\" alt=\"\" style=\"width: 50%;padding:7px 1px 1px 1px;\">\n"
                + "        </th>\n"
                + "      </tr>\n"
                + "    </thead>\n"
                + "\n"
                + "    <tbody style=\"margin-top: -2rem; padding:0; color:#001D4C;\">\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <hr style=\"height: 2px; background-color: #042355;\">\n"
                + "\n"
                + "          <h1>Hola, "+parts[1]+",</h1>\n"
                + "\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"font-size: 18px;\">\n"
                + "        <td>\n"
                + "          <div style=\"width:100%; margin:0 auto;\">\n"
                + "            <p style=\"text-align:left; line-height: 1.7rem; \">\n"
                + "              Hemos recibido tu reclamo Nº "+parts[0]+" el día "+parts[3]+".\n"
                + "            </p>\n"
                + "            <p>\n"
                + parts[2]
                + "            </p>\n"
                + "            <p>\n"
                + "              Si tuvieras alguna consulta o sugerencia, estamos a tu disposición.\n"
                + "            </p>\n"
                + "          </div>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr>\n"
                + "        <td>\n"
                + "          <img src=\"https://i.pinimg.com/originals/72/90/71/7290710ba1e0497b3b4245d859db9b96.png\" alt=\"\" style=\"float:right; height:4rem; margin-top:50px;\">\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"height:30px;\">\n"
                + "        <td>\n"
                + "          <hr style=\"height: 2px;background-color: #042355; \">\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr>\n"
                + "        <td>\n"
                + "          <img src=\"https://i.pinimg.com/originals/d7/60/9c/d7609c4009428e592e561306f49446ab.png\" alt=\"\" style=\"float:right; height:4rem;\">\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "    </tbody>\n"
                + "\n"
                + "  </table>\n"
                + "</body>\n"
                + "\n"
                + "</html>\n";

        return cuerpo;

    }
    
    // ---- agregado --- /
        public String cuerpolibrorec_respcli_1(String detallestr) {

        String cuerpo = "<!DOCTYPE html>\n"
                + "<html lang=\"es\" xmlns=\"http://www.w3.org/1999/xhtml\">\n"
                + "\n"
                + "<head>\n"
                + "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n"
                + "  <title>Respuesta-Cliente</title>\n"
                + "  <style type=\"text/css\">\n"
                + "    @media (max-width: 550px) {\n"
                + "\n"
                + "      .button {\n"
                + "        font-size: 10px !important;\n"
                + "      }\n"
                + "\n"
                + "      .tr {\n"
                + "        /* background-color: teal; */\n"
                + "\n"
                + "      }\n"
                + "\n"
                + "      td {\n"
                + "        height: 8rem !important;\n"
                + "        font-size;\n"
                + "        5rem;\n"
                + "      }\n"
                + "\n"
                + "      img {\n"
                + "        display: block;\n"
                + "\n"
                + "      }\n"
                + "\n"
                + "    }\n"
                + "  </style>\n"
                + "</head>\n"
                + "\n"
                + "<body yahoo=\"\" style=\"font-family:arial;\">\n"
                + "\n"
                + "  <table style=\"margin:0 auto; max-width:600px;\">\n"
                + "    <thead>\n"
                + "\n"
                + "      <tr>\n"
                + "        <th style=\"background-color: #042355;\" >\n"
                + "          <img class=\"img\" src=\"https://i.pinimg.com/originals/74/e2/c1/74e2c1ea5c12c19f2996f1158fe3a60a.png\" alt=\"\" style=\"width: 50%;padding:7px 1px 1px 1px;\">\n"
                + "        </th>\n"
                + "      </tr>\n"
                + "    </thead>\n"
                + "\n"
                + "    <tbody style=\"margin-top: -2rem; padding:0; color:#001D4C;\">\n"
                + "\n"
                + "      <tr style=\"\">\n"
                + "        <td>\n"
                + "          <hr style=\"height: 2px; background-color: #042355;\">\n"
                + "\n"
                + "          <p style=\"line-height: 1rem;\">\n"
                + "\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"font-size: 18px;\">\n"
                + "        <td>\n"
                + "          <div style=\"width:100%; margin:0 auto;\">\n"
                + "            <p>\n"
                + detallestr
                + "            </p>\n"
                + "            <p>\n"
                + "              Si tuvieras alguna consulta o sugerencia, estamos a tu disposición.\n"
                + "            </p>\n"
                + "          </div>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr>\n"
                + "        <td>\n"
                + "          <img src=\"https://i.pinimg.com/originals/72/90/71/7290710ba1e0497b3b4245d859db9b96.png\" alt=\"\" style=\"float:right; height:4rem; margin-top:50px;\">\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"height:30px;\">\n"
                + "        <td>\n"
                + "          <hr style=\"height: 2px;background-color: #042355; \">\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr>\n"
                + "        <td>\n"
                + "          <img src=\"https://i.pinimg.com/originals/d7/60/9c/d7609c4009428e592e561306f49446ab.png\" alt=\"\" style=\"float:right; height:4rem;\">\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "    </tbody>\n"
                + "\n"
                + "  </table>\n"
                + "</body>\n"
                + "\n"
                + "</html>\n";

        return cuerpo;

    }
}
