/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bee.plataforma.correo;

import com.bee.plataforma.config.EncryptDecryptUtil;
import java.net.URLEncoder;

/**
 *
 * @author Lealva
 */
public class CuerpoEnvioRecPassword {

    public String cuerpoEnvio(String codigo_ciente, String cliente) throws Exception {
        String id = URLEncoder.encode(EncryptDecryptUtil.encryptPhrase(codigo_ciente), "UTF-8");
        String nombre = URLEncoder.encode(EncryptDecryptUtil.encryptPhrase(cliente), "UTF-8");

        String cadena = "<!DOCTYPE html>\n"
                + "<html lang=\"es\" xmlns=\"http://www.w3.org/1999/xhtml\">\n"
                + "\n"
                + "<head>\n"
                + "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n"
                + "  <link href=\"https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700&display=swap\" rel=\"stylesheet\">\n"
                + "  <title>Restablecer contraseña</title>\n"
                + "\n"
                + "</head>\n"
                + "\n"
                + "<body yahoo=\"\" style=\"font-family: 'Montserrat', sans-serif;\">\n"
                + "\n"
                + "  <table style=\"margin:0 auto;\">\n"
                + "    <thead>\n"
                + "      <tr>\n"
                + "        <th>\n"
                + "          <img class=\"img\" src=\"https://i.pinimg.com/originals/55/a4/71/55a4715b084a0b359f60f18dde96b793.png\" alt=\"Cineplanet At Work \" style=\"width: 500px ; padding-top: 2rem;\">\n"
                + "        </th>\n"
                + "      </tr>\n"
                + "    </thead>\n"
                + "    <tbody style=\"margin-top: -16px; padding:0;\">\n"
                + "\n"
                + "      <tr>\n"
                + "        <td>\n"
                + "          <p style=\"text-align: center;\n"
                + "            color: #555;\n"
                + "            font-size: 20px;\n"
                + "            font-weight: 500;\n"
                + "            padding-bottom:0;\n"
                + "            margin-bottom: 16px;\n"
                + "            line-height: normal;\n"
                + "            margin-top:24px;\">\n"
                + "            Has solicitado un restablecimiento de contraseña <br>\n"
                + "            para tu cuenta de Cineplanet At Work. <br>\n"
                + "            Dale click al enlace para establecer una nueva contraseña.\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr>\n"
                + "        <td>\n"
                + "          <p style=\"text-align: center;\n"
                + "            font-size: 20px;\n"
                + "            font-weight: 400;\n"
                + "            padding-bottom:0;\n"
                + "            margin-bottom: 16px;\n"
                + "            line-height: normal;\n"
                + "            margin-top:24px;\">\n"
                + "            <a href=\"http://localhost:8084/plataforma/plataforma.password?id=" + id + "&usu=" + nombre +" target=\"_blank\">linkrestblecercontraseñaatwork</a>\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr>\n"
                + "        <td>\n"
                + "          <p style=\"text-align: center;\n"
                + "            color: #555;\n"
                + "            font-size: 20px;\n"
                + "            font-weight: 500;\n"
                + "            padding-bottom:0;\n"
                + "            margin-bottom: 16px;\n"
                + "            line-height: normal;\n"
                + "            margin-top:24px;\">\n"
                + "            Si no deseas restablecer tu contraseña <br>ignora este mensaje.\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "\n"
                + "\n"
                + "      <tr style=\"height:30px;\">\n"
                + "        <td>\n"
                + "          <hr style=\"height: 4px;\n"
                + "          background-color: #177799;\n"
                + "          border: none;\n"
                + "          width: 600px;\n"
                + "          margin-top:1.5rem;\n"
                + "          \">\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "\n"
                + "      <tr style=\"height:30px;\">\n"
                + "        <td>\n"
                + "          <p style=\"text-align: center;\n"
                + "           color: #555;\n"
                + "           font-size: 18px;\n"
                + "           font-weight: 400;\n"
                + "           padding-bottom:0;\n"
                + "           line-height: normal;\n"
                + "           margin-bottom: 0;\n"
                + "          margin-top:20px;\">\n"
                + "            Si tuvieras alguna duda, escríbenos a:\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr style=\"height:30px;\">\n"
                + "        <td>\n"
                + "          <p style=\"text-align: center;\n"
                + "          color: #555;\n"
                + "          font-size: 18px;\n"
                + "          font-weight: bold;\n"
                + "          padding-bottom:0;\n"
                + "          line-height: normal;\n"
                + "          margin-bottom: 16px;\n"
                + "          margin-top:0;\n"
                + "          \">\n"
                + "            atencionalcliente@bee.com.pe\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr>\n"
                + "        <td>\n"
                + "          <p style=\"text-align: center;\n"
                + "          color: #555;\n"
                + "            font-size: 18px;\n"
                + "            font-weight: 400;\n"
                + "            margin-bottom: 0;\n"
                + "            line-height: normal;\n"
                + "            margin-top:.32px;\">\n"
                + "            o llámanos al:\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "      <tr>\n"
                + "        <td>\n"
                + "          <p style=\"text-align: center;\n"
                + "          color: #555;\n"
                + "          font-size: 18px;\n"
                + "          font-weight: bold;\n"
                + "          padding-bottom:0;\n"
                + "          line-height: normal;\n"
                + "          margin-bottom: 16px;\n"
                + "          margin-top:0;\">\n"
                + "            (01) 640-9699\n"
                + "          </p>\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "\n"
                + "      <tr>\n"
                + "        <td>\n"
                + "          <img class=\"img\" src=\"https://i.pinimg.com/originals/b2/31/80/b231803c987e717c9e444489ac7fb480.jpg\" alt=\"\" style=\"\n"
                + "        width: 700px;\n"
                + "        padding-top: 20px;\n"
                + "        display: block;\n"
                + "        margin: 0 auto;\n"
                + "        \">\n"
                + "        </td>\n"
                + "      </tr>\n"
                + "\n"
                + "\n"
                + "    </tbody>\n"
                + "\n"
                + "  </table>\n"
                + "</body>\n"
                + "\n"
                + "</html>";
        return cadena;
    }

    public static void main(String[] args) throws Exception {
        String id = URLEncoder.encode(EncryptDecryptUtil.encryptPhrase("1"), "UTF-8");
        String cliente = URLEncoder.encode(EncryptDecryptUtil.encryptPhrase("Alicia Esmeral Cerna"), "UTF-8");
        //String cliente = EncryptDecryptUtil.decryptPhrase("0uWNNv9HMKFbu+F0D97HsteJpjLEfTfy");
        System.out.println("Mensaje" + id);
        System.out.println("Mensaje" + cliente);
    }
}
